#FROM swamykonanki/baserobo
#ADD RFW/robot /robot
#ADD RFW/run.sh /
#RUN chmod -R +x /robot
#RUN chmod +x /run.sh
#CMD ["/test.sh"]

FROM swamykonanki/baserobo
ADD robot /robot
ADD run.sh /
RUN chmod -R +x /robot
RUN chmod +x /run.sh
